name: Sync to edbltn.github.io

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Push to GitHub Pages
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git remote add edbltn https://$PAT@github.com:edbltn/edbltn.github.io.git
        git push edbltn main:main --force
