name: Sync to edbltn.github.io

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Push to edbltn.github.io
      run: |
        # Create a new branch for syncing
        git checkout -b sync-branch

        # Remove .github directory
        git rm -r --cached .github
        git commit -m "Remove .github directory for sync"

        # Add remote and push
        git remote add edbltn git@github.com:edbltn/edbltn.github.io.git
        git push edbltn sync-branch:main --force

        # Clean up
        git checkout main
        git branch -D sync-branch
