name: Sync to edbltn.github.io

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Push to edbltn.github.io
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git remote add edbltn git@github.com:edbltn/edbltn.github.io.git
        git push edbltn main:main --force
